### ISSUE TITLE
add new Optional: MaterialAdmin

### ISSUE THREAD

**Issue by soclanovtsy** [DJPlaya/Forlix-Floodcheck-Redux#9]
**Describe the Feature you'd like to be added**
add new Optional: [MaterialAdmin](https://github.com/SB-MaterialAdmin/NewServer)

**Describe Alternatives you've considered**
-

**Additional context**
-

**Comment by DJPlaya** [comment]
@soclanovtsy 
Before adding this, i need to know some Stuff first which i cannot find out myself because i do not speak Russian and i did not pay for hlmod.ru:
- Whats Material Admin?
- Is SB-MaterialAdmin an Addition or even Addon to MaterialAdmin?
- Is SB-MaterialAdmin something new or are there other Editions of it?
- Which Plugins need to be running in order to have the Natives available? For SB++, this is 'sbpp_main.smx' because it contains all Natives
- Is SB-MaterialAdmin supposed to run along with with SB2.0 or SB++?

**Comment by soclanovtsy** [comment]
Please wait 2-3 days, I will try to answer you in detail

**Comment by IIIef** [comment]
Good day, MaterialAdmin is the same as SourceBans++. I just need to write everything in Natives as in MaterialAdmin only correctly, I can't do it. Please do this under MaterialAdmin.

**Comment by soclanovtsy** [comment]
thank you very much, sorry for not answering, covid19 is guilty. I'll check it out today

**Comment by IIIef** [comment]
Thank you for your answer and thank you very much.

**Comment by soclanovtsy** [comment]
IIIef, Sorry, I did not understand the answer first. I thought I already did forlix under material addmin and I need to do a test)))

I will answer in detail after tomorrow the first question, I will try. I want this plugin to work under materialadmin.

**Comment by soclanovtsy** [comment]
> @soclanovtsy
> Before adding this, i need to know some Stuff first which i cannot find out myself because i do not speak Russian and i did not pay for hlmod.ru:
> 
> * Whats Material Admin?
> * Is SB-MaterialAdmin an Addition or even Addon to MaterialAdmin?
> * Is SB-MaterialAdmin something new or are there other Editions of it?
> * Which Plugins need to be running in order to have the Natives available? For SB++, this is 'sbpp_main.smx' because it contains all Natives
> * Is SB-MaterialAdmin supposed to run along with with SB2.0 or SB++?

1. SB-MaterialAdmin = refork SB ++. Now it is completely independent, a separate system.
2.  materialadmin.smx = main plugin, but for muts, gags there is a separate plugin = ma_basecomm.smx
3. Native English the language is all here - https://github.com/SB-MaterialAdmin/NewServer/blob/master/addons/sourcemod/scripting/include/materialadmin.inc (all descriptions for each native are available)

**Comment by soclanovtsy** [comment]
I tried to tie your plugin to MaterialAdmin myself, but I didn’t succeed. Little experience. Or not in all files changed. Now the plugin does not start.
[forlix_floodcheck_redux_ma.zip](https://github.com/DJPlaya/Forlix-Floodcheck-Redux/files/4646726/forlix_floodcheck_redux_ma.zip)
I’m sure how the author will succeed easily, and we’ll check just the plugin’s work and write it off right away.

**Comment by IIIef** [comment]
Thanks, but there is a mistake. 

forlix_floodcheck_redux_ma.sp(280) : warning 204: symbol is assigned a value that is never used: "q_bmabasecomm"

**Comment by soclanovtsy** [comment]
> Thanks, but there is a mistake.
> 
> forlix_floodcheck_redux_ma.sp(280) : warning 204: symbol is assigned a value that is never used: "q_bmabasecomm"

Ну я об этом и написал как раз, ждем автора плагина, надеюсь сможет добавить MA в свой нужный я считаю плагин. А мы проверим и ответим ему тут все ли работает.

**Comment by DJPlaya** [comment]
Thanks for the Information, i will implement this into FFCR and KACR soon.

**Comment by DJPlaya** [comment]
Ive uploaded an early Version to the nightly Branch, i would be happy if someone could confirm that its working fine.
In this Build, only the Ban and Offline Ban Functions are implemented, i will add support for the Mute/Gag Stuff later

**Comment by IIIef** [comment]
I installed it and it still works without errors.

**Comment by DJPlaya** [comment]
The latest Nightly Update includes Support for Client Mutes, use "ffcr_test" to mute all Clients.
Please do not do this alone and get one other Client on the Server to check if everyone is properly muted.
Please send me the Chat Output after you have used "ffcr_test", it contains useful Information.
Also tell me if there is anything in the Error Logs, ty ^^

**Comment by IIIef** [comment]
If I understand correctly then ffcr_test should have been entered in the server console?)

ffcr_test
[Debug][FFCR] Client '╔к╩Я╩Яс┤ЬъЬ▒ъЬ▒╩Ь╔кс┤П╔┤<7463><[U:1:453050922]><>' is Muted
[Debug][FFCR] Setting Client to muted...
L 06/05/2020 - 23:56:12: [SM] Exception reported: Mute Error: Player is not an admin.
L 06/05/2020 - 23:56:12: [SM] Blaming: materialadmin.smx
L 06/05/2020 - 23:56:12: [SM] Call stack trace:
L 06/05/2020 - 23:56:12: [SM]   [0] ThrowNativeError
L 06/05/2020 - 23:56:12: [SM]   [1] Line 304, materialadmin/native.sp::Native_OffSetClientMuteType
L 06/05/2020 - 23:56:12: [SM]   [3] MAOffSetClientMuteType
L 06/05/2020 - 23:56:12: [SM]   [4] Line 101, FFCR/voiceloopback.sp::FFCR_UnMute
L 06/05/2020 - 23:56:12: [SM]   [5] Line 204, forlix_floodcheck_redux.sp::FFCR_TEST

**Comment by DJPlaya** [comment]
Thanks, it seemd to be a Typo i have made. Please try it again.
Also, was that client muted before the execution of the command?

**Comment by IIIef** [comment]
No this player is not in the Mut)

ffcr_test
[Debug][FFCR] Client '-$-Aim41K-$-<7477><[U:1:847804659]><>' is Unmuted
[Debug][FFCR] Setting Client to muted...
L 06/06/2020 - 00:37:06: Log file closed.
L 06/06/2020 - 00:37:06: Error log file session closed.
L 06/06/2020 - 00:37:06: [SM] Exception reported: Mute Error: Player is not an admin.
L 06/06/2020 - 00:37:06: [SM] Blaming: materialadmin.smx
L 06/06/2020 - 00:37:06: [SM] Call stack trace:
L 06/06/2020 - 00:37:06: [SM]   [0] ThrowNativeError
L 06/06/2020 - 00:37:06: [SM]   [1] Line 304, materialadmin/native.sp::Native_OffSetClientMuteType
L 06/06/2020 - 00:37:06: [SM]   [3] MAOffSetClientMuteType
L 06/06/2020 - 00:37:06: [SM]   [4] Line 101, FFCR/voiceloopback.sp::FFCR_UnMute
L 06/06/2020 - 00:37:06: [SM]   [5] Line 204, forlix_floodcheck_redux.sp::FFCR_TEST

**Comment by IIIef** [comment]
ffcr_test
[Debug][FFCR] Client '-$-Aim41K-$-<7477><[U:1:847804659]><>' is Unmuted
[Debug][FFCR] Setting Client to Muted
L 06/06/2020 - 00:43:39: [materialadmin.smx] "Console<0><Console><Console>" mute "-$-Aim41K-$- ([U:1:847804659] IP_95.28.36.255)" (minutes "0") (reason "voice loopback")
L 06/06/2020 - 00:43:39: [SM] Exception reported: Language phrase "Voice loopback not allowed!
You have been muted." not found (arg 4)
L 06/06/2020 - 00:43:39: [SM] Blaming: forlix_floodcheck_redux.smx
L 06/06/2020 - 00:43:39: [SM] Call stack trace:
L 06/06/2020 - 00:43:39: [SM]   [0] PrintToChat
L 06/06/2020 - 00:43:39: [SM]   [1] Line 123, FFCR/voiceloopback.sp::FFCR_UnMute
L 06/06/2020 - 00:43:39: [SM]   [2] Line 210, forlix_floodcheck_redux.sp::FFCR_TEST
[MA]  Added to the database -$-Aim41K-$-

**Comment by IIIef** [comment]
Forgot to update the plugin)

**Comment by IIIef** [comment]
> Thanks, it seemd to be a Typo i have made. Please try it again.
> Also, was that client muted before the execution of the command?

Yes, he was in the Mut database.

**Comment by DJPlaya** [comment]
@IIIef 
Okay, with the updated Version, he should be unmuted when he is muted, and muted when he is unmuted. It kinda swaps the States, if it works both Ways, the test is finished successful

**Comment by IIIef** [comment]
There were errors, the server CSGO.


L 06/18/2020 - 22:45:03: [SM] Exception reported: Argument index is invalid: 5
L 06/18/2020 - 22:45:03: [SM] Blaming: forlix_floodcheck_redux.smx
L 06/18/2020 - 22:45:03: [SM] Call stack trace:
L 06/18/2020 - 22:45:03: [SM]   [0] VFormat
L 06/18/2020 - 22:45:03: [SM]   [1] Line 18, FFCR/stocks.sp::FFCR_Ban
L 06/18/2020 - 22:45:03: [SM]   [2] Line 42, FFCR/nameflood.sp::FloodCheckName
L 06/18/2020 - 22:45:03: [SM]   [3] Line 29, FFCR/events.sp::Event_PlayerChangename
L 06/18/2020 - 22:55:27: Error log file session closed.

**Comment by DJPlaya** [comment]
Seems it was a small Typo ^^, please try again

**Comment by IIIef** [comment]
Thank you, I updated it, there are no errors yet.

**Comment by DJPlaya** [comment]
Did you tried 'ffcr_test' ? If that works fine, i can deploy this one to the stable Branch

**Comment by IIIef** [comment]
L 06/22/2020 - 20:32:39: [SM] Exception reported: Language phrase "Voice loopback not allowed!
You have been muted." not found (arg 4)
L 06/22/2020 - 20:32:39: [SM] Blaming: forlix_floodcheck_redux.smx
L 06/22/2020 - 20:32:39: [SM] Call stack trace:
L 06/22/2020 - 20:32:39: [SM]   [0] PrintToChat
L 06/22/2020 - 20:32:39: [SM]   [1] Line 123, FFCR/voiceloopback.sp::FFCR_UnMute
L 06/22/2020 - 20:32:39: [SM]   [2] Line 219, forlix_floodcheck_redux.sp::FFCR_TEST

**Comment by IIIef** [comment]
Updated, and checked ffcr_test no more errors, checked on CSGO server and TF2. When entering ffcr_test all on the server sends to permanent mute, is it normal?)

**Comment by DJPlaya** [comment]
Good that you remind me of that, ive had Mutes from Material Admin on Permanent for testing.
Ive changed that in the following Version.
MaterialAdmin dosent allow Session Mutes, because of this, all Mutes are either as long as the left Map Time, or 60min if there is no Time or it is over 6 Hours.
Ive already openen an Issue on their GitHub, lets hope they will integrate it some Time later.
